# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN atd at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt GH_TOKEN=[OAUTH-TOKEN] -r Intenet2/grouper --add env.global
#

# Grouper CI pipeline:
#
# 1) For every commit in master, shallow git clone
# 2) Build the whole project with Maven against the build matrix expansion. If any build fails, email committer and abort remaining steps
# 3) Run tests (CAN'T DO THIS - THERE IS A 50 MINUTE TIME LIMIT FOR ANY STAGE)
#      - Start a local hsql db (todo or postgres via docker container?)
#      - use gsh to boostrap the initial database
#      - execute tests (capture output to a file?)
#      - abort if any tests fail
# 4) Deploy
#      - Abort if not a tagged build
#      - Parse version number out of tag (GROUPER_RELEASE_a.b.c...)
#      - mvn versions:set the pom versions to this version
#      - Rebuild project. If fails, abort remaining steps
#      - Deploy to the Maven release-stage repo
#      - Return success
#
# Note, it needs to be tagged at the time of deployment, so the window for tagging is small

language: java
os: linux
# (DEPRECATED) sudo: false
branches:
  only:
  - GROUPER_2_5_BRANCH
  - /^GROUPER_RELEASE_(\d+\.)+\d+(rc\d+)?$/
jdk:
  - openjdk8

  #stages:
#  - compile
#  - test
#  #- deploy_release
#  ##- name: deploy_release
#  ##  if: tag =~ ^GROUPER_RELEASE_(\d+\.)+\d+$

#jobs:
#  include:
#    - stage: test
#      script: chmod u+x travis/travis-test.sh && travis/travis-test.sh
#    - stage: deploy_release
#      script: chmod u+x travis/deploy-to-sonatype.sh && travis/deploy-to-sonatype.sh

before_install:
  # Import gpg keys
  - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in ./travis/gpg-signingkey.asc.enc -out ./travis/gpg-signingkey.asc -d
  - gpg --import ./travis/gpg-signingkey.asc
install: skip
before_script:
  - cp -p travis/mvn.settings.xml $HOME/.m2/settings.xml
  - ./travis/init-travis-build.sh
  - export JAVA_OPTS="-Xmx2048m"
script:
  - mvn -f ./grouper-parent clean package
  # Uncomment the install if resuming snapshot deployments
  #- mvn -f ./grouper-parent install -B -V -q
##after_success:
##- chmod -R 777 travis/deploy-to-sonatype.sh
##- travis/deploy-to-sonatype.sh
##- mvn -f ./grouper-parent clean test cobertura:cobertura coveralls:cobertura -Dlicense.skip=true -DskipTests=true
##- chmod -R 777 travis/javadocs-ghpages.sh
##- travis/javadocs-ghpages.sh
before_deploy:
  # deployment script will change the version from snapshot, so clean first
  - mvn -f ./grouper-parent clean
deploy:
  provider: script
  script: travis/deploy-to-sonatype.sh
  #(DEPRECATED) skip_cleanup: true
  on:
    #branch: travis
    tags: true

env:
  global:
    ## These are encodings for legacy travis-ci.org -- GH_TOKEN, SONATYPE_USER, SONATYPE_PWD
    # - secure: "XmmxnbDo/FeIE2O5M6YMSKjULOgLPDDx79mcfRTf79Fvjiqw2yJBrheLwR2sYs4+6uw7Pe0FkKUXtyRrcK31JvWTuqvwTs08MgMt42VPx7xGX+96i8hN6QTF8D1B1YYRJnnXrtOrhqSbpm+jffw3PiK4f5fcKDntSaMbPUiVRDg="
    # - secure: "MjJBfBqMpetCZ0PmcISetMxHAEcC83EawXmJuCW/F7RrCk8tBY+YglYSRHFqj/LDcwLHdDPuPOLHEv/RKPyqQvjYfJICwpQugMRrIUPuoXsg57xoSP36DBNG8qVCa5rS1qLaUb42fsvYXd9ufjKu8c0Eihq8pbz+yrXxKgvSpIU="
    # - secure: "kJDUzde56X0epK70R9e2hN7Q6nfHyk0ixDOynPYJh01hREyLl/7Zm3V6dv5nfGhFbCoJDcqkTlUsl26ixrmmr4AUhh+fKkQVO8Pjj8z9fR6Y1lukJ2v2RVDRzN0sR5cCqKGd2yr9VW9s+4JinfcBQNj2dxwhCKddj+NPPM9o0CE="
    ## Encodings for travis-ci.com -- SONATYPE_USER, SONATYPE_PWD (GH_TOKEN is not currently being used)
    - secure: "MyNvB2yF1jlOQSv7sW060x6hboFsCh0Nr9BYl2FmNsg8AEMX7T7ajiVDi8iIMbhVb56qIP3PM3kdBPINBIfkcaXO4qWL3O1MUNiyujKrAdwAyzPEfn/GQvvPCly859J5Zj0hzoI8BrP+jwsXXdVVM6jzytrejaDfECq754mheDp1Wi7NRqOmZL+rGSQdIpKGei7T8wSeVs3h0mM0iYRdMSztZL9KZlJRUXGrsZXvLNljEZaDB5rBDLFqNmbApZxDGLFUMVnUU7wNGZg16I34+eEtGqaSWCCr6rWtC8MfKOnD+5a1WjqXvoDAANHsthTdtFz/5FwxJxTy4vPbSYXmRHrEHY8m9JLK8BQIesX4sDAQZOoWQ3huu8cl9bupsjSnlNqggrrIOp7q17vZF+7r5ZZbXlDQ56bqzJF9dXjDE5Ydl9b9cgDSLuR95TEn45EuYvpqUOt2+SbssczIG8yERO3PbMcvntIWuisdbJ6LO7MecvccG78fJVev6y17icw1Y+ubThh3iviYDm5gzfH4Q7BMYytr2BmvNDGUCU2OqFJjPOAgV9MVEWlsUcOzxwZ2lEtAJDUKvfWwLkyMGckU0OxmdTfZ66y2jeoWzK6yFRSrk/K2Eb9aYkW2i+DAXg+GkK1Q0nk/gJzMiBRqNgXvnTv/HKQ1sMfEhZnu1dqKz44="
    - secure: "KcgmhaC9REkaIC32fdxvKVuS4mdVKwui2kuj0bO+owqrjdlMlJTP3/Rak37pkaKzGVrxmekJNLjhVTWf+WBfXhRGmhTnem+GoMC5e0rkuJse56hNRAkUngvWpJD4db7zHbtiGkvE226FJk5LsG4Kws0rMBWaNmD55NkWJoNRdYmsdYWcU8D725LKkVpnihA9WneQABGamAsm53hw3lLleAchDtB6JDDzSrSsNPVY99IriYXxVOZeKK1c6IWC4BHlSVBHKI3iy4EOu1IUtjkVYfUwp0inPjjE3T91xEDF/XBImAEaIhZXfagMMjgTwaVPFcQi3RHwjVkLazG030h/pRo7yQZLS5N90LqbXFtiZqc2aDAWgtGBswybbwJwiPUgt82p6otYTJoTMiy8azL2QMttuSkUNXFlu7aCskj+WtexqwA6ZzvG/hUdRvRf2Bu0JO6a85WFQFl5kPqY3ObHIzUljXhg5tJPDM8k9SEuL253RtXFOWUx+RxuxVI0UpjSTRqZoXpFSFS4kx1Zh6Kj0oMcTEss096e57pXjDaQjZn8khaV25zbhyT86N9Ti7zbxjyVs5MjnbN9yltbW80jsNej+ECVfH2Atn6wC6nziZFT2TI2ug2+jOSo4zL1Hy5Uilq9YDxRXaBoLaiEWKXl7IP9B/deBf9WXFRorC8A4Fg="
